# Project mdev rules.
# Auto mount removable MMC/SD partitions on add/remove events.
mmcblk[0-9]+p[0-9]+ 0:0 660 @/usr/sbin/sd_hotplug.sh add $MDEV
mmcblk[0-9]+p[0-9]+ 0:0 660 $/usr/sbin/sd_hotplug.sh remove $MDEV
